class Player {
  late final String firstName;
  late final String lastName;
  late final String nwsrsId; //Not the autogenerated id but NWSRS id
  late final int rating;
  late final String status;
  Player(
      {required this.firstName,
      required this.lastName,
      required this.nwsrsId,
      required this.rating,
      required this.status});
  Player.fromFireStore(Map<String, dynamic> json)
      : this(
          firstName: json['first_name']! as String,
          lastName: json['last_name']! as String,
          nwsrsId: json['ID']! as String,
          rating: json['rating']! as int,
          status: json['status']! as String,
        );
  Map<String, dynamic> toJson() {
    return {
      'first_name': firstName,
      'last_name': lastName,
      'rating': rating,
      'status': status
    };
  }
}
